routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('employee', EmployeesController::class)->middleware(['auth']);
Route::get('/dashboard', function () {
    return redirect('employee');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'address',
        'phone',
        'department',
        'position',
        'salary',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeePostRequest;
use App\Models\Employee;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::paginate(10);
        return  view('employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeePostRequest $request)
    {
        // sanitize input
        $args = [
            'name' => FILTER_SANITIZE_STRING,
            'address' => FILTER_SANITIZE_STRING,
            'phone' => FILTER_SANITIZE_STRING,
            'department' => FILTER_SANITIZE_STRING,
            'position' => FILTER_SANITIZE_STRING,
            'salary' => FILTER_SANITIZE_NUMBER_FLOAT,
        ];
        $sanitizedReq = filter_var_array($request->validated(), $args);

        Employee::create($sanitizedReq);
        return redirect()->route('employee.index')->with('success', 'Employee added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //not implemented
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('employees.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeePostRequest $request, Employee $employee)
    {
        // sanitize input
        $args = [
            'name' => FILTER_SANITIZE_STRING,
            'address' => FILTER_SANITIZE_STRING,
            'phone' => FILTER_SANITIZE_STRING,
            'department' => FILTER_SANITIZE_STRING,
            'position' => FILTER_SANITIZE_STRING,
            'salary' => FILTER_SANITIZE_NUMBER_FLOAT,
        ];
        $sanitizedReq = filter_var_array($request->validated(), $args);

        $employee->update($sanitizedReq);
        return redirect()->route('employee.index')
            ->with('success', 'Employee updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        return redirect()->route('employee.index')
            ->with('success', 'Employee deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/employees/create.blade.php
@extends('dashboard')

@section('content')
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="flex justify-center items-center m-1 font-medium py-1 px-2 bg-white rounded-md text-red-700 bg-red-100 border border-red-300 ">
                <div slot="avatar">
                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-octagon w-5 h-5 mx-2">
                        <polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
                        <line x1="12" y1="8" x2="12" y2="12"></line>
                        <line x1="12" y1="16" x2="12.01" y2="16"></line>
                    </svg>
                </div>
                <div class="text-xl font-normal  max-w-full flex-initial">
                    {{ $error }}
                </div>
            </div>
        @endforeach
    @endif

    <div class="pb-4"><a href="{{ route('employee.index') }}" class="ml-3 text-xl bg-green-500 hover:bg-green-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline">Back</a></div>
    <form id="createForm" action="{{ route('employee.store') }}" method="POST" class="max-w-xl m-4 p-10 bg-white rounded shadow-xl">
        @csrf
        <p class="text-gray-800 font-medium">Add employee</p>
        <div class="mt-2 group">
            <label class="block text-sm text-gray-00" for="name">Name</label>
            <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" id="name" name="name" type="text" required="" placeholder="Name" aria-label="name">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="address">Address</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="address" name="address" type="text" required="" placeholder="Address" aria-label="address">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="phone">Phone #</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="phone" name="phone" required="" placeholder="Phone number" aria-label="phone">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="department">Department</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="department" name="department" type="text" required="" placeholder="Department" aria-label="department">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="position">Position</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="position" name="position" type="text" required="" placeholder="Position" aria-label="position">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="salary">Salary</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="salary" name="salary" required="" placeholder="Salary" aria-label="salary">
        </div>
        <div class="mt-4">
            <button type="submit" class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Add employee</button>
        </div>
    </form>
@endsection
@section('javascript')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#createForm').validate({
                rules: {
                    name: {
                        required: true,
                        maxlength: 255,
                    },
                    address: {
                        required: true,
                        maxlength: 255,
                    },
                    phone: {
                        required: true,
                        maxlength: 255,
                    },
                    department: {
                        required: true,
                        maxlength: 255,
                    },
                    position: {
                        required: true,
                        maxlength: 255,
                    },
                    salary: {
                        required: true,
                        number: true,
                        min: 0
                    },
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('text-red-600');
                    element.closest('.group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('bg-red-600');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('bg-red-600');
                }
            });
        });
    </script>
@endsection

resources/views/employees/edit.blade.php
@extends('dashboard')

@section('content')
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="flex justify-center items-center m-1 font-medium py-1 px-2 bg-white rounded-md text-red-700 bg-red-100 border border-red-300 ">
                <div slot="avatar">
                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-octagon w-5 h-5 mx-2">
                        <polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
                        <line x1="12" y1="8" x2="12" y2="12"></line>
                        <line x1="12" y1="16" x2="12.01" y2="16"></line>
                    </svg>
                </div>
                <div class="text-xl font-normal  max-w-full flex-initial">
                    {{ $error }}
                </div>
            </div>
        @endforeach
    @endif

    <div class="pb-4"><a href="{{ route('employee.index') }}" class="ml-3 text-xl bg-green-500 hover:bg-green-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline">Back</a></div>
    <form id="editForm" action="{{ route('employee.update', $employee->id) }}" method="POST" class="max-w-xl m-4 p-10 bg-white rounded shadow-xl">
        @csrf
        @method('PUT')
        <p class="text-gray-800 font-medium">Edit employee</p>
        <div class="mt-2 group">
            <label class="block text-sm text-gray-00" for="name">Name</label>
            <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" value="{{ $employee->name }}" id="name" name="name" type="text" required="" placeholder="Name" aria-label="name">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="address">Address</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" value="{{ $employee->address }}" id="address" name="address" type="text" required="" placeholder="Address" aria-label="address">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="phone">Phone #</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" value="{{ $employee->phone }}" id="phone" name="phone" required="" placeholder="Phone number" aria-label="phone">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="department">Department</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" value="{{ $employee->department }}" id="department" name="department" type="text" required="" placeholder="Department" aria-label="department">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="position">Position</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" value="{{ $employee->position }}" id="position" name="position" type="text" required="" placeholder="Position" aria-label="position">
        </div>
        <div class="mt-2 group">
            <label class=" block text-sm text-gray-600" for="salary">Salary</label>
            <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" value="{{ $employee->salary }}" id="salary" name="salary" required="" placeholder="Salary" aria-label="salary">
        </div>
        <div class="mt-4">
            <button type="submit" class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Edit employee</button>
        </div>
    </form>
@endsection
@section('javascript')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#editForm').validate({
                rules: {
                    name: {
                        required: true,
                        maxlength: 255,
                    },
                    address: {
                        required: true,
                        maxlength: 255,
                    },
                    phone: {
                        required: true,
                        maxlength: 255,
                    },
                    department: {
                        required: true,
                        maxlength: 255,
                    },
                    position: {
                        required: true,
                        maxlength: 255,
                    },
                    salary: {
                        required: true,
                        number: true,
                        min: 0
                    },
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('text-red-600');
                    element.closest('.group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('bg-red-600');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('bg-red-600');
                }
            });
        });
    </script>
@endsection

resources/views/employees/index.blade.php
@extends('dashboard')

@section('content')
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <div class="flex justify-center items-center m-1 font-medium py-1 px-2 bg-white rounded-md text-green-700 bg-green-100 border border-green-300 ">
                <div slot="avatar">
                    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle w-5 h-5 mx-2">
                        <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                        <polyline points="22 4 12 14.01 9 11.01"></polyline>
                    </svg>
                </div>
                <div class="text-xl font-normal  max-w-full flex-initial">
                    {{ $message }}
                </div>
            </div>
        </div>
    @endif
    <div class="pb-4"><a href="{{ route('employee.create') }}" class="float-right mr-3 text-sm bg-green-500 hover:bg-green-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline">Add Employee</a></div>
    <table class="w-full text-md bg-white shadow-md rounded mb-4">
        <thead>
        <tr class="border-b">
            <th class="text-left p-3 px-5">Name</th>
            <th class="text-left p-3 px-5">Address</th>
            <th class="text-left p-3 px-5">Phone #</th>
            <th class="text-left p-3 px-5">Department</th>
            <th class="text-left p-3 px-5">Position</th>
            <th class="text-left p-3 px-5">Salary</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($employees as $employee)
        <tr class="border-b hover:bg-orange-100 bg-gray-100">
            <td class="p-3 px-5">{{ $employee->name }}</td>
            <td class="p-3 px-5">{{ $employee->address }}</td>
            <td class="p-3 px-5">{{ $employee->phone }}</td>
            <td class="p-3 px-5">{{ $employee->department }}</td>
            <td class="p-3 px-5">{{ $employee->position }}</td>
            <td class="p-3 px-5">{{ $employee->salary }}</td>
            <td class="p-3 px-5 flex justify-end">
                <a title="edit" href="{{ route('employee.edit', $employee->id) }}" class="mr-3 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline">Edit</a>
                <form action="{{ route('employee.destroy', $employee->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" title="delete" class="text-sm bg-red-500 hover:bg-red-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
    {!! $employees->links() !!}
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
        @yield('javascript')
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Logout') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Logout') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>